version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ./wait-for-it.sh -t 15 postgres:5432 -- bash entrypoint.sh
    env_file: .env.local
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    stdin_open: true
    tty: true
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app-development
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis/data
  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - app
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - fileName: .env.local
  #   environment:
  #     - RAILS_ENV=development
  #     - SIDEKIQ_CONFIG=./config/sidekiq.yml
  #   entrypoint: bash -c "bundle exec sidekiq -c 2 -d -e development"

volumes:
  pg_data:
